/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SonicsRouteImport } from './routes/sonics'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as OverlayRouteImport } from './routes/overlay'
import { Route as MarqueeRouteImport } from './routes/marquee'
import { Route as FlowEditorRouteImport } from './routes/flow-editor'
import { Route as AppRouteImport } from './routes/App'
import { Route as IndexRouteImport } from './routes/index'

const SonicsRoute = SonicsRouteImport.update({
  id: '/sonics',
  path: '/sonics',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayRoute = OverlayRouteImport.update({
  id: '/overlay',
  path: '/overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const MarqueeRoute = MarqueeRouteImport.update({
  id: '/marquee',
  path: '/marquee',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowEditorRoute = FlowEditorRouteImport.update({
  id: '/flow-editor',
  path: '/flow-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/App',
  path: '/App',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/App': typeof AppRoute
  '/flow-editor': typeof FlowEditorRoute
  '/marquee': typeof MarqueeRoute
  '/overlay': typeof OverlayRoute
  '/preview': typeof PreviewRoute
  '/sonics': typeof SonicsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/App': typeof AppRoute
  '/flow-editor': typeof FlowEditorRoute
  '/marquee': typeof MarqueeRoute
  '/overlay': typeof OverlayRoute
  '/preview': typeof PreviewRoute
  '/sonics': typeof SonicsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/App': typeof AppRoute
  '/flow-editor': typeof FlowEditorRoute
  '/marquee': typeof MarqueeRoute
  '/overlay': typeof OverlayRoute
  '/preview': typeof PreviewRoute
  '/sonics': typeof SonicsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/App'
    | '/flow-editor'
    | '/marquee'
    | '/overlay'
    | '/preview'
    | '/sonics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/App'
    | '/flow-editor'
    | '/marquee'
    | '/overlay'
    | '/preview'
    | '/sonics'
  id:
    | '__root__'
    | '/'
    | '/App'
    | '/flow-editor'
    | '/marquee'
    | '/overlay'
    | '/preview'
    | '/sonics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  FlowEditorRoute: typeof FlowEditorRoute
  MarqueeRoute: typeof MarqueeRoute
  OverlayRoute: typeof OverlayRoute
  PreviewRoute: typeof PreviewRoute
  SonicsRoute: typeof SonicsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sonics': {
      id: '/sonics'
      path: '/sonics'
      fullPath: '/sonics'
      preLoaderRoute: typeof SonicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay': {
      id: '/overlay'
      path: '/overlay'
      fullPath: '/overlay'
      preLoaderRoute: typeof OverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marquee': {
      id: '/marquee'
      path: '/marquee'
      fullPath: '/marquee'
      preLoaderRoute: typeof MarqueeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow-editor': {
      id: '/flow-editor'
      path: '/flow-editor'
      fullPath: '/flow-editor'
      preLoaderRoute: typeof FlowEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/App': {
      id: '/App'
      path: '/App'
      fullPath: '/App'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  FlowEditorRoute: FlowEditorRoute,
  MarqueeRoute: MarqueeRoute,
  OverlayRoute: OverlayRoute,
  PreviewRoute: PreviewRoute,
  SonicsRoute: SonicsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
